In [30]:
import random
import numpy as np

In [234]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [235]:
y.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [239]:
y.reshape(-1, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [244]:
y = np.arange(3)
y

array([0, 1, 2])

In [245]:
y.shape

(3,)

In [1]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [249]:
yy = y[:, np.newaxis]
yy

array([[0],
       [1],
       [2]])

In [248]:
yy.shape

(3, 1)

In [251]:
y[np.newaxis, :]

array([[0, 1, 2]])

In [252]:
b = np.array([[1,1], [2,2], [3,3]])
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [253]:
b.flatten()

array([1, 1, 2, 2, 3, 3])

In [254]:
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [255]:
b.T

array([[1, 2, 3],
       [1, 2, 3]])

In [256]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [261]:
a = a.reshape(2, -1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [262]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [263]:
a = np.array([1, -4])
b = np.array([3, 6])

a

array([ 1, -4])

In [264]:
b

array([3, 6])

In [265]:
a * b

array([  3, -24])

In [266]:
np.dot(a, b)

np.int64(-21)

In [267]:
a.dot(b)

np.int64(-21)

In [268]:
np.sum(a*b)

np.int64(-21)

In [270]:
u = np.array([1,2,0,-1])
v = np.array([2,2,3,4])

u

array([ 1,  2,  0, -1])

In [271]:
v

array([2, 2, 3, 4])

In [272]:
np.sum(u*v)

np.int64(2)

In [273]:
u.dot(v)

np.int64(2)

In [274]:
X = [2,3]
W = [[1,2,1], [2,5,1]]
np.matmul(X, W)



array([ 8, 19,  5])

In [275]:
A = np.array([[1,-2], [3, -1]])
B = np.array([[2, -3, 4], [0, -1, 2]])
C = np.eye(2)
D = np.array([[0, 6, 4], [3, 2, 1], [2, 1, 0]])



In [276]:
A @ A

array([[-5,  0],
       [ 0, -5]])

In [277]:
A @ B

array([[ 2, -1,  0],
       [ 6, -8, 10]])

In [278]:
A @ C

array([[ 1., -2.],
       [ 3., -1.]])

In [279]:
C @ C

array([[1., 0.],
       [0., 1.]])

In [280]:
B @ D

array([[-1, 10,  5],
       [ 1,  0, -1]])

In [281]:
D @ D

array([[26, 16,  6],
       [ 8, 23, 14],
       [ 3, 14,  9]])

In [5]:
import numpy as np
from collections import defaultdict

dict = defaultdict(lambda x: np.zeros(4))
dict[0] = 3
dict[0]

3

In [7]:
a = [1,2,3]
b = [1,2,3]

np.dstack([a, b])

array([[[1, 1],
        [2, 2],
        [3, 3]]])

In [9]:
a, b = np.meshgrid(np.arange(1,3), np.arange(1,3))

np.dstack([a, b])


array([[[1, 1],
        [2, 1]],

       [[1, 2],
        [2, 2]]])