In [20]:
import numpy as np
import commonfuc as cf


cf.one_hot(4, 3)


array([[0., 0., 0., 1.]])

In [25]:
import tensorflow as tf, keras

input_size = 16
output_size = 4
main_model = keras.Sequential([
    keras.layers.Input(shape=(input_size,)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(output_size)
])

main_model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['accuracy']
)

# main_model.build(input_shape=(None, input_size))

In [26]:
onehot = cf.one_hot(16, 3)
onehot

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
# main_model(onehot)

In [28]:
main_model.predict(onehot)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


array([[-0.01161482,  0.22277185, -0.00119496,  0.10113042]],
      dtype=float32)

In [30]:
main_model(onehot)

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[-0.01161482,  0.22277185, -0.00119496,  0.10113042]],
      dtype=float32)>

In [29]:
main_model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 128)            │         2,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 4)              │           516 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,692 (10.52 KB)

 Trainable params: 2,692 (10.52 KB)

 Non-trainable params: 0 (0.00 B)

In [33]:
onehot = np.identity(16)[0:1][0]
onehot

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])